### ISSUE TITLE
cron job to backup database

### ISSUE THREAD

**Issue by iff** [iff/all-o-stasis-avers#49]
https://cloud.google.com/kubernetes-engine/docs/how-to/cronjobs

@wereHamster's input:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lightning-stats-scraper
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lightning-stats-scraper
            image: gcr.io/the-moments-we-shared/lightning-stats-scraper:latest
            resources:
              requests:
                cpu: 1m
                memory: 1Mi
            env:
            - name: LND
              value: "caurea.org"
            - name: INFLUXDB
              value: "influxdb"
          restartPolicy: OnFailure
```

Für rethinkdb backup würde ich ein docker image erstellen welches rethinkdb cli client + gsutil drin hat, und dann den dump in einen bucket kopiert. Per retention policy kannst du im bucket definieren dass die backups nach X monaten automatisch gelöscht werden sollen.
